modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Tejty/GameDiscs/issues"
[[mods]]
modId="gamediscs"
version="${mod_version}"
displayName="${mod_name}"

#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="gamediscs.png"
#credits=""
authors="${mod_authors}"

description='''${mod_description}'''

#[[mixins]]
#config="gamediscs.mixins.json"

[[dependencies.gamediscs]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.gamediscs]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"